version: "3"
services:
  chromedriver:
    image: selenium/standalone-chrome:4.1.2-20220317
    build:
      context: .
    shm_size: "2gb"
    ports: 
      - "4444:4444"

  steam_parser:
    build: .
    links:
      - chromedriver