node {
    stage('Clone repository') {
        checkout scm
    }

    stage("Build image") {
        sh "mvn spring-boot:build-image -D spring.profiles.active=prod -D S3_BUCKET_NAME=loljoa-resource-bucket"
    }
    
    stage("Docker login") {
        environment {
            DOCKER_HUB_LOGIN = credentials('docker-hub')
        }
        sh 'docker login --username=$DOCKER_HUB_LOGIN_USR --password=$DOCKER_HUB_LOGIN_PSW'
    }

    stage("Image rename") {
        sh "docker tag lck_schedule_apiserver:0.0.1-SNAPSHOT loljoa/lck_schedule_apiserver:0.0.1-SNAPSHOT"
    }


    stage("Image push") {
        sh "docker push loljoa/lck_schedule_apiserver:0.0.1-SNAPSHOT"
    }

    stage("Resource cleanup") {
        sh "docker image prune -a"
    }
}